// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3RWAMaIx883LRf8_MfE70izSUFZzYcDM',
    appId: '1:909775527453:web:1afa4ae7ad3732e553b0f4',
    messagingSenderId: '909775527453',
    projectId: 'movie-app-9db3f',
    authDomain: 'movie-app-9db3f.firebaseapp.com',
    storageBucket: 'movie-app-9db3f.appspot.com',
    measurementId: 'G-2BNMK2R3RK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIdH4OV0VtBLPfr6Yi_FO6SzOnK7KwtHg',
    appId: '1:909775527453:android:fc64b4e40b81a38153b0f4',
    messagingSenderId: '909775527453',
    projectId: 'movie-app-9db3f',
    storageBucket: 'movie-app-9db3f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVDrxi7DKWGeCHqRh0R_Mcip1ETNBLX_w',
    appId: '1:909775527453:ios:641a1ab5f7b9693c53b0f4',
    messagingSenderId: '909775527453',
    projectId: 'movie-app-9db3f',
    storageBucket: 'movie-app-9db3f.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVDrxi7DKWGeCHqRh0R_Mcip1ETNBLX_w',
    appId: '1:909775527453:ios:641a1ab5f7b9693c53b0f4',
    messagingSenderId: '909775527453',
    projectId: 'movie-app-9db3f',
    storageBucket: 'movie-app-9db3f.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3RWAMaIx883LRf8_MfE70izSUFZzYcDM',
    appId: '1:909775527453:web:2189dd123d10f80d53b0f4',
    messagingSenderId: '909775527453',
    projectId: 'movie-app-9db3f',
    authDomain: 'movie-app-9db3f.firebaseapp.com',
    storageBucket: 'movie-app-9db3f.appspot.com',
    measurementId: 'G-L592MHT5LM',
  );

}