// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQRJa9P7SMYhe8LOLovA4nSybECDh7n4A',
    appId: '1:430442903099:web:8c7daa629bfc2337ab4e1e',
    messagingSenderId: '430442903099',
    projectId: 'movie-update-babd8',
    authDomain: 'movie-update-babd8.firebaseapp.com',
    storageBucket: 'movie-update-babd8.appspot.com',
    measurementId: 'G-N9TJ9ED9RJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0vB8fLYd7JIa2Mzu5iFMMKjuJqU_FWhU',
    appId: '1:430442903099:android:26851c554cd2b080ab4e1e',
    messagingSenderId: '430442903099',
    projectId: 'movie-update-babd8',
    storageBucket: 'movie-update-babd8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlgtpxmp4jn7qgZqS-qnA6sNwAf9-N3cA',
    appId: '1:430442903099:ios:cd29031939db7903ab4e1e',
    messagingSenderId: '430442903099',
    projectId: 'movie-update-babd8',
    storageBucket: 'movie-update-babd8.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlgtpxmp4jn7qgZqS-qnA6sNwAf9-N3cA',
    appId: '1:430442903099:ios:cd29031939db7903ab4e1e',
    messagingSenderId: '430442903099',
    projectId: 'movie-update-babd8',
    storageBucket: 'movie-update-babd8.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQRJa9P7SMYhe8LOLovA4nSybECDh7n4A',
    appId: '1:430442903099:web:13a597cd970d6a60ab4e1e',
    messagingSenderId: '430442903099',
    projectId: 'movie-update-babd8',
    authDomain: 'movie-update-babd8.firebaseapp.com',
    storageBucket: 'movie-update-babd8.appspot.com',
    measurementId: 'G-VYWML7WT8C',
  );
}
